// <auto-generated />
using System;
using ENGER.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ENGER.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316232048_AddClient")]
    partial class AddClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ENGER.Domain.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_CARTAO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("NM_BANDEIRA");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("integer")
                        .HasColumnName("NR_MES_EXPIRACAO");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("integer")
                        .HasColumnName("NR_ANO_EXPIRACAO");

                    b.Property<string>("LastCardNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("NR_FINAL_CARTAO");

                    b.Property<string>("MercadoPagoCardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CD_MP_CARTAO");

                    b.Property<string>("MercadoPagoCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CD_MP_CUSTOMER");

                    b.HasKey("CardId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CARTOES", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_CLIENTE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_CELULAR");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("CIDADE");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ENTRADA");

                    b.Property<string>("FantasyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_FANTASIA");

                    b.Property<string>("FederativeUnit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("UF");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("RGIENumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_IERG");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_RAZAO");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CPF_CNPJ");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("CEP");

                    b.HasKey("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CLIENTES", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_EMPRESA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ENTRADA");

                    b.Property<string>("FantasyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_FANTASIA");

                    b.Property<string>("FederativeUnit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("UF");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("RGIENumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_IERG");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_RAZAO");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CPF_CNPJ");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<Guid?>("SubscriptionCode")
                        .HasColumnType("uuid")
                        .HasColumnName("CD_ASSINATURA");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("CEP");

                    b.HasKey("CompanyId");

                    b.HasIndex("SubscriptionCode")
                        .IsUnique();

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_FUNCIONARIO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ADMISSAO");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_CELULAR");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_FUNCIONARIO");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ENTRADA");

                    b.Property<string>("NumberGeneralRegistration")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("RG");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("CD_CARGO");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CPF");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PositionId");

                    b.ToTable("FUNCIONARIOS", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_CARGO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PositionId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("DescriptionPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DS_CARGO");

                    b.HasKey("PositionId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CARGOS", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_ASSINATURA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_VENCIMENTO");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PROXIMA_COBRANCA");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PAGAMENTO");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_INICIO");

                    b.Property<int>("StatusSubscription")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ASSINATURA");

                    b.Property<Guid>("SubscriptionCode")
                        .HasMaxLength(40)
                        .HasColumnType("uuid")
                        .HasColumnName("CD_CHAVE");

                    b.Property<string>("SubscriptionIdMercadoPago")
                        .HasColumnType("text")
                        .HasColumnName("CD_ASSINATURA_MP");

                    b.Property<int>("TypeSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("TypeSubscriptionId");

                    b.ToTable("ASSINATURA", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("SubscriptionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_TP_ASSINATURA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionTypeId"));

                    b.Property<string>("DescriptionSubscriptionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("DS_TP_ASSINATURA");

                    b.Property<int>("SubscriptionMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NR_MESES");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionMonth"));

                    b.Property<decimal>("SubscriptionValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VL_ASSINATURA");

                    b.HasKey("SubscriptionTypeId");

                    b.ToTable("TIPO_ASSINATURA", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CD_USUARIO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("Admin")
                        .HasColumnType("integer")
                        .HasColumnName("ADMIN");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("EntryDate")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ENTRADA");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<DateTime>("UpdateDate")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NM_USUARIO");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Card", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Client", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Company", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Subscription", null)
                        .WithOne()
                        .HasForeignKey("ENGER.Domain.Entities.Company", "SubscriptionCode")
                        .HasPrincipalKey("ENGER.Domain.Entities.Subscription", "SubscriptionCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ENGER.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Position", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany()
                        .HasForeignKey("TypeSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.User", b =>
                {
                    b.HasOne("ENGER.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ENGER.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
